### ISSUE TITLE
CSS not inlined with ultrahtml version 1.0.0-next.4.

### ISSUE THREAD

**Issue by Leftium** [natemoo-re/satori-html#8]
When `npm install satori-html` is run in a fresh project, ultrahtml version 1.0.0-next.4 is installed as a dependency. With ultrahtml version 1.0.0-next.4, CSS is not inlined as expected. CSS is inlined with ultrahtml version 1.0.0-next.3.

Either the incompatibility should be fixed, or ultrahtml version pinned to version 1.0.0-next.3.

```
import { html } from 'satori-html';

const markup = html`<main /><style>main{width:42px;}</style>`

console.log(JSON.stringify(markup.props.children, null, 4))
```

**Expected:** (ultrahtml version 1.0.0-next.3)

```
[
    {
        "type": "main",
        "props": {
            "style": {
                "width": "42px"
            },
            "children": []
        }
    }
]
```

**Actual:** (ultrahtml version 1.0.0-next.4)

```
[
    {
        "type": "main",
        "props": {
            "children": []
        }
    },
    {
        "type": "style",
        "props": {
            "children": "main{width:42px;}"
        }
    }
]

```

**Comment by spences10** [comment]
Credit to @geoffrich for the workaround for this!

Add this override to your `package.json` file if you're using `pnpm`:

```json
"pnpm": {
	"overrides": {
		"ultrahtml": "1.0.0-next.3"
	}
}
```

**Comment by KiwiKilian** [comment]
Seems to work fine again with [ultrahtml@1.0.0](https://github.com/natemoo-re/ultrahtml/releases/tag/v1.0.0)! 🚀

**Comment by natemoo-re** [comment]
Thanks I totally missed this! Pushing a fix soon.
